### ISSUE TITLE
Computing completeness score?

### ISSUE THREAD

**Issue by jihyechoi77** [chihkuanyeh/concept_exp#2]
Hi! I'd like to ask for clarification on how you implemented the computation of completeness score from the paper.
It seems that the method "get_completeness" of "ipca_v2.py" doesn't really compute the completeness score but just repeats the training of topic model, as in "topic_model_new" of "ipca_v2.py".
Thanks for your help in advance!

**Comment by cobermai** [comment]
I would have the same question. I would look forward to receive an answer.

**Comment by chihkuanyeh** [comment]
Hi, the get_completeness of ipca_v2.py does calculate the completeness score. As mentioned in the paper, the completeness score is calculated by the accuracy of a model whose input is vc(x) (and minus random accuracy), divided by the accuracy of the original model (and minus random accuracy). The code in ipca_v2.py calculates the accuracy of a model whose input is vc(x), as the model's layer before vc(x) is fixed in the code (see some parts of the model is set to be fixed).

The remaining steps is to minus random accuracy and divide by (the original accuracy minus random accuracy), which we omit in the code.
