### ISSUE TITLE
Which layer from Inception-V3

### ISSUE THREAD

**Issue by jihyechoi77** [chihkuanyeh/concept_exp#4]
Hi Chih-Kuan,

Which layer of Inception-V3 did you use to generate concepts for AwA2 classification task in your paper?
Also, what were the corresponding receptive field size and offset (which were 32 and 116, respectively, for toy example: https://github.com/chihkuanyeh/concept_exp/blob/master/toy_helper_v2.py#L49)?

I couldn't find these details from the paper and the codes, so would greatly appreciate your reply!
Thanks.

**Comment by chihkuanyeh** [comment]
Hi, 

In our appendix (https://proceedings.neurips.cc/paper/2020/file/ecb287ff763c169694f682af52c1f309-Supplemental.pdf), we mentioned that we apply on mix_5d layer.
(Choice of h,g, p15): The intermediate layer (which effect sh) can be chosen depending on the size of the nearest neighbor patch the user would like to visualize, since this size depends on the receptive field of the feature layer. Deeper layers have larger receptive fields, while shallower layers have smaller receptive field size. In AwA experiments, we select Mixed_5d layer so that the receptive field is 127*127, which is half of the original image size and capable of capturing both larger and smaller concepts. We also tested on mixed_5c and resulting concepts are shown.
This supplement is not updated on Arxiv which is a mistake by me.
